service: zlmlcz

plugins:
#  - serverless-offline
  - serverless-plugin-warmup
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1 # Ireland
  stage: production
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

custom:
  custom:
    warmup:
      schedule: 'rate(1 minute)'
      prewarm: true
  prune: # prune old Lambda functions
    automatic: true
    number: 3 # number of versions to keep

package:
  excludeDevDependencies: false
  exclude:
    - ./**
  include:
    - .next/**
    - node_modules/** # TODO: remove
    - services/**
    - static/**
    - package.json

functions:
  blog:
    warmup: true
    handler: services/Lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: GET
          cors: true
          integration: lambda-proxy
      - http:
          path: /
          method: GET
          cors: true
          integration: lambda-proxy
